### PR TITLE
Adding Anthropic + simplifying model calling across Palm, Replicate, OpenAI

### PR DESCRIPTION
**Pull request by krrishdholakia**
Hi @snakajima, 

Noticed you're using a couple different llm providers in `generateResponse`. I'm working on `litellm` (simple library to standardize LLM API Calls - https://github.com/BerriAI/litellm) and was wondering if we could be helpful. 

Simplified your model calling and added support for anthropic-claude models. 

Would love to know if this helps. Also adding a screenshot of the code working post changes. 

Screenshot 2023-08-02 at 1 53 41 PM

### CODE REVIEW

**Comment by krrishdholakia** [comment]
bump @snakajima

**Comment by krrishdholakia** [comment]
Hi @snakajima - I can see your calling replicate, etc. but looks like litellm wasn't helpful? 

What was litellm missing to be useful to you? Any feedback here would be helpful.

**Comment by snakajima** [comment]
Nothing wrong with litellm. Supporting different type of LLMs is quite important for us, and we need to rapidly evolve it. This is why we are building our own, not relying on third party libraries like litellm. We appreciate your pull request, but we are not able to merge it.

**Comment by krrishdholakia** [comment]
@snakajima is there anything we could add on our end to make litellm more useful for you?

**Pull request closed without merging**
